class MainPage:
    page_title = ".heading"
    add_remove_elements = "Add/Remove Elements"
    basic_auth = "Basic Auth"
    challenging_dom = "Challenging DOM"
    check_boxes = "Checkboxes"
    context_menu = "Context Menu"
    forgot_password = "Forgot Password"
    drop_down = "Dropdown"
    dynamic_controls = "Dynamic Controls"
    form_authentication = "Form Authentication"
    javascript_alerts = "JavaScript Alerts"
    key_presses = "Key Presses"
    notification_message = "Notification Messages"
