class MainPage:
    page_title = ".heading"
    add_remove_elements = "[href='/add_remove_elements/']"
    basic_auth = "[href='/basic_auth']"
    challenging_dom = "[href='/challenging_dom']"
    check_boxes = "[href='/checkboxes']"
    context_menu = "href='/context_menu']"
    forgot_password = "[href='/forgot_password']"
    drop_down = "[href='/dropdown']"
    dynamic_controls = "[href='/dynamic_controls']"
    form_authentication = "[href='/login']"
    javascript_alerts = "[href='/javascript_alerts']"
    key_presses = "[href='/key_presses']"
    notification_message = "[href='/notification_message']"